### ISSUE TITLE
BubbleSort com sentinela

### ISSUE THREAD

**Issue by bcribas** [bcribas/benchmark-ordenacao#4]
Falta uma implementação do BubbleSort que tenha o sentinela de trocas, para que o algoritmo aproveite o estado quase ordenado do vetor.

**Comment by chfleury** [comment]
professor eu fiz um que tem uma flag, caso ele passe por algum dos loops e nao faça nenhuma troca, ele da break, seria isso?
https://github.com/chfleury/data-structures/blob/main/Sort%20Algorithms/bubble_sort.c

**Comment by bcribas** [comment]
> professor eu fiz um que tem uma flag, caso ele passe por algum dos loops e nao faça nenhuma troca, ele da break, seria isso?
> https://github.com/chfleury/data-structures/blob/main/Sort%20Algorithms/bubble_sort.c

É isso mesmo Fleury! Agora você pode fazer um pull request do `bubblesort.c` com a sua modificação. Pode chamar o arquivo de `bubblesortsentinela.c`.

Seria um /plus / as modificações no `Makefile` e no `main.h` (mas não são necessárias ).

[]s

**Comment by bcribas** [comment]
Resolvido com o commit https://github.com/bcribas/benchmark-ordenacao/commit/b71ef5d8c816aa1f168716cd3f122efe63b8a814
